# Generated by Django 5.2.3 on 2025-07-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_alter_task_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='due_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
